import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
// import App from './App'
import Script from 'next/script'
import dynamic from 'next/dynamic'

const inter = Inter({ subsets: ['latin'] })

const ComponentWithNoSSR = dynamic(
  () => import('./App'),
  { ssr: false }
)


export default function Home() {
  console.log('render home')
  return (
    <>
      <Head>
        <title>React Web component hello</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <script src='/components.js'></script>
      <main className={styles.main}>
        <ComponentWithNoSSR />
      </main>
    </>
  )
}
